---

- name: Check local gpg commands
  ansible.builtin.command:
    cmd: "{{ item }}"
  changed_when: false
  delegate_to: localhost
  vars:
    ansible_become: false
  with_items:
    - "gpg --version"

- name: Import keys from keyserver
  ansible.builtin.command:
    cmd: "gpg --batch  --keyserver {{ gpg_keyserver }} --recv-keys {{ item }}"
  with_items: "{{ gpg_import_keys }}"
  changed_when: false
  when:
    - (gpg_import_keys is defined) and (gpg_import_keys | length > 0)
  delegate_to: localhost

- name: Set backup random suffix
  ansible.builtin.set_fact:
    backup_random_suffix: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

- name: Set backup host prefix
  ansible.builtin.set_fact:
    backup_host_prefix: "{{ inventory_hostname | replace('.', '_') }}"

- name: Create backup tarballs
  ansible.builtin.command:
    cmd: "tar czf {{ remote_backup_temp_path }}/{{ item | replace('/', '_') | replace('*', '@') }}_{{ backup_random_suffix }}.tgz {{ item }}"
  with_items: "{{ remote_backup_paths }}"
  changed_when: false

- name: Fetch tarballs
  ansible.builtin.fetch:
    src: "{{ remote_backup_temp_path }}/{{ item | replace('/', '_') | replace('*', '@') }}_{{ backup_random_suffix }}.tgz"
    dest: "{{ local_backup_temp_path }}/{{ backup_host_prefix }}_{{ item | replace('/', '_') | replace('*', '@') }}_{{ backup_random_suffix }}.tgz"
    flat: true
  with_items: "{{ remote_backup_paths }}"

- name: Safely delete remote tarballs
  ansible.builtin.command:
    cmd: "shred -uz {{ remote_backup_temp_path }}/{{ item | replace('/', '_') | replace('*', '@') }}_{{ backup_random_suffix }}.tgz"
  with_items: "{{ remote_backup_paths }}"
  changed_when: false

- name: Generate recipents list
  set_fact:
    gpg_recipients_params: "{{ gpg_recipients_params | default('') + '-r ' + item + ' '}}"
  loop: "{{ gpg_recipients }}"

- name: Encrypt backup files
  ansible.builtin.shell: >
      set -o pipefail &&
      cat {{ local_backup_temp_path }}/{{ backup_host_prefix }}_{{ item | replace('/', '_') | replace('*', '@') }}_{{ backup_random_suffix }}.tgz
      | gpg --batch --trust-model always --encrypt {{ gpg_recipients_params }} -o {{ local_backup_destination }}/{{ backup_host_prefix }}_{{ item | replace('/', '_')
      | replace('*', '@') }}_{{ backup_random_suffix }}.tgz.gpg
  with_items: "{{ remote_backup_paths }}"
  delegate_to: localhost
  vars:
    ansible_become: false
  changed_when: false

- name: Safely delete local tarballs
  ansible.builtin.command:
    cmd: "shred -uz {{ local_backup_temp_path }}/{{ backup_host_prefix }}_{{ item | replace('/', '_') | replace('*', '@') }}_{{ backup_random_suffix }}.tgz"
  with_items: "{{ remote_backup_paths }}"
  delegate_to: localhost
  vars:
    ansible_become: false
  changed_when: false
