---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "docker.io/geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
