---
- name: Verify
  hosts: all
  tasks:
    - name: List generated backups
      ansible.builtin.shell: "ls -l tmp/*.gpg"
      delegate_to: localhost
      changed_when: false
      register: ls

    - name: Encrypted files output
      ansible.builtin.debug:
        msg: "{{ ls.stdout }}"
